#!/bin/bash
source "$HOME/scripts/utils/colors"

echo "${yellow}Backing up XCom: Started"

cp "/Users/jcheung/Library/Application Support/Feral Interactive/XCOM Enemy Unknown/XEW/SaveData/save300" "/Users/jcheung/Library/Application Support/Feral Interactive/XCOM Enemy Unknown/XEW/save300.bak"

echo "${green}Backing up XCom: Finished"
echo "${reset}"
