#!/bin/bash
source "$HOME/scripts/utils/colors"
source "$HOME/scripts/game-utils/config"

echo "${yellow}Restoring XCom: Started${reset}"

cp "$STASH_PATH/save300.bak" "/Users/jcheung/Library/Application Support/Feral Interactive/XCOM Enemy Unknown/XEW/SaveData/save300"

echo "${green}Restoring XCom: Finished${reset}"
